
import { SubsidyProgram, NotificationItem, UserProfile } from './types';

export const MOCK_USER_PROFILE: UserProfile = {
  name: 'Gan Zi Xiang',
  icNumber: '880515-14-5678',
  householdSize: 4,
  householdIncome: 4500,
  address: '123, Jalan Merdeka, Taman Sejahtera, 40000 Shah Alam, Selangor',
  ageCategory: 'adult',
  vehicles: [
    { plate: 'WXY 1234', roadTaxExpiry: '2024-06-15' },
  ],
  isOku: false,
  hasChildren: true,
  childrenCount: 2,
  hasSeniorDependents: true,
  seniorDependentsCount: 1,
  myDigitalIdVerified: true,
};

const rawSubsidyWallets: Omit<SubsidyProgram, 'color'>[] = [
  {
    id: 'sara',
    programName: 'Subsidi Asas Rahmah',
    programCode: 'SARA',
    category: 'groceries',
    icon: '🛒',
    currentBalance: 85.50,
    totalAllocated: 200,
    monthlyCredit: 100,
    nextCreditDate: '2024-02-01',
    expiryDate: '2024-02-28',
    remainingQuota: null,
    quotaUnit: null,
    eligibilityStatus: 'eligible',
    applicationStatus: 'approved',
    isVerified: true,
    transactions: [
      { id: 't1', date: '2024-01-28', description: 'Mydin Shah Alam', amount: -45.60, type: 'debit', merchant: 'Mydin' },
      { id: 't2', date: '2024-01-25', description: 'Econsave Klang', amount: -32.80, type: 'debit', merchant: 'Econsave' },
      { id: 't3', date: '2024-01-01', description: 'Monthly Credit', amount: 100, type: 'credit' },
    ],
    allowedItems: ['Rice', 'Cooking Oil', 'Sugar', 'Flour', 'Eggs', 'Chicken', 'Fish', 'Vegetables'],
    allowedCategories: ['groceries', 'essentials'],
    programDescription: 'SARA (Subsidi Asas Rahmah) provides targeted subsidies for essential food items to eligible Malaysian households in the B40 income group.',
    eligibilityCriteria: [
      'Malaysian citizen',
      'B40 household income (below RM4,850/month)',
      'Must have valid MyKad',
      'Registered in eKasih database',
    ],
    benefitAmount: 'RM100 per month',
    renewalRules: 'Automatic renewal if eligibility criteria are met during annual review.',
    conditions: [
      'Subsidy can only be used for approved essential items',
      'Must use at participating retailers',
      'Cannot be converted to cash',
    ],
    limitations: [
      'Maximum RM100 per month',
      'Unused balance expires at month end',
      'Limited to essential groceries only',
    ],
    faq: [
      { question: 'Where can I use SARA?', answer: 'SARA can be used at participating retailers including Mydin, Econsave, and other approved stores.' },
      { question: 'What items are covered?', answer: 'Essential items such as rice, cooking oil, sugar, flour, eggs, chicken, fish, and vegetables.' },
    ],
  },
  {
    id: 'str',
    programName: 'Sumbangan Tunai Rahmah',
    programCode: 'STR',
    category: 'groceries',
    icon: '💵',
    currentBalance: 250,
    totalAllocated: 500,
    monthlyCredit: 0,
    nextCreditDate: '2024-03-01',
    expiryDate: null,
    remainingQuota: null,
    quotaUnit: 'RM',
    eligibilityStatus: 'eligible',
    applicationStatus: 'approved',
    isVerified: true,
    transactions: [
      { id: 't4', date: '2024-01-15', description: 'Payment - Utility Bill', amount: -150, type: 'debit' },
      { id: 't5', date: '2024-01-01', description: 'STR Phase 1 Credit', amount: 250, type: 'credit' },
      { id: 't6', date: '2023-12-01', description: 'STR Phase 2 Credit', amount: 250, type: 'credit' },
    ],
    allowedItems: ['Rice', 'Cooking Oil', 'Flour', 'Sugar', 'Baby Formula', 'Diapers', 'School Supplies'],
    programDescription: 'Sumbangan Tunai Rahmah (STR) is a cash assistance program to help B40 families cope with rising cost of living.',
    eligibilityCriteria: [
      'Malaysian citizen',
      'B40 household income',
      'Registered in LHDN database',
    ],
    benefitAmount: 'Up to RM2,500 per year',
    renewalRules: 'Annual application required.',
    conditions: ['Must update income status annually'],
    limitations: ['Disbursed in phases throughout the year'],
    faq: [
      { question: 'How is STR paid?', answer: 'STR is credited directly to your registered bank account in phases.' },
    ],
  },
  {
    id: 'budi95',
    programName: 'Subsidi Petrol BUDI',
    programCode: 'BUDI 95',
    category: 'fuel',
    icon: '⛽',
    currentBalance: 120.40,
    totalAllocated: 200,
    monthlyCredit: 200,
    nextCreditDate: '2024-02-01',
    expiryDate: '2024-02-28',
    remainingQuota: 120,
    quotaUnit: 'litres',
    eligibilityStatus: 'eligible',
    applicationStatus: 'approved',
    isVerified: true,
    alertMessage: '⛽ 80 litres used this month',
    alertType: 'info',
    transactions: [
      { id: 't7', date: '2024-01-27', description: 'Shell Seksyen 7', amount: -45.60, type: 'debit', merchant: 'Shell' },
      { id: 't8', date: '2024-01-20', description: 'Petronas Subang', amount: -34.00, type: 'debit', merchant: 'Petronas' },
      { id: 't9', date: '2024-01-01', description: 'Monthly Credit', amount: 200, type: 'credit' },
    ],
    allowedCategories: ['RON95 Petrol'],
    programDescription: 'BUDI 95 provides targeted fuel subsidies for RON95 petrol to eligible Malaysian motorists.',
    eligibilityCriteria: [
      'Malaysian citizen',
      'Own a vehicle under 1600cc (car) or 150cc (motorcycle)',
      'B40/M40 income group',
      'Valid driving license',
    ],
    benefitAmount: 'Up to 200 litres per month',
    renewalRules: 'Automatic monthly renewal based on quota.',
    conditions: [
      'Only for RON95 petrol',
      'Vehicle must be registered under applicant',
      'Must refuel at participating stations',
    ],
    limitations: [
      'Maximum 200 litres monthly',
      'Car engine capacity max 1600cc',
      'Motorcycle engine capacity max 150cc',
    ],
    faq: [
      { question: 'How do I refuel?', answer: 'Scan the QR code at participating petrol stations. The subsidy will be auto-deducted.' },
    ],
  },
  {
    id: 'bwe',
    programName: 'Bantuan Warga Emas',
    programCode: 'BWE',
    category: 'elderly',
    icon: '👴',
    currentBalance: 500,
    totalAllocated: 500,
    monthlyCredit: 500,
    nextCreditDate: '2024-02-01',
    expiryDate: null,
    remainingQuota: null,
    quotaUnit: 'RM',
    eligibilityStatus: 'not_eligible',
    applicationStatus: 'not_started',
    isVerified: true,
    transactions: [],
    programDescription: 'Bantuan Warga Emas provides monthly assistance to senior citizens aged 60 and above.',
    eligibilityCriteria: [
      'Malaysian citizen',
      'Aged 60 years and above',
      'No fixed income or pension',
      'Not receiving other government assistance',
    ],
    benefitAmount: 'RM500 per month',
    renewalRules: 'Automatic renewal upon eligibility verification.',
    conditions: ['Must update status every 6 months'],
    limitations: ['Cannot receive if already on pension'],
    faq: [
      { question: 'Who qualifies?', answer: 'Citizens aged 60+ without fixed income or pension.' },
    ],
  },
  {
    id: 'epoku',
    programName: 'Elaun Pekerja OKU',
    programCode: 'EPOKU',
    category: 'oku',
    icon: '♿',
    currentBalance: 450,
    totalAllocated: 450,
    monthlyCredit: 450,
    nextCreditDate: '2024-02-01',
    expiryDate: null,
    remainingQuota: null,
    quotaUnit: 'RM',
    eligibilityStatus: 'not_eligible',
    applicationStatus: 'not_started',
    isVerified: true,
    transactions: [],
    programDescription: 'EPOKU provides monthly allowance to registered OKU individuals who are employed.',
    eligibilityCriteria: [
      'Registered OKU with JKM',
      'Currently employed',
      'Income below RM4,000/month',
    ],
    benefitAmount: 'RM450 per month',
    renewalRules: 'Annual verification of employment status required.',
    conditions: ['Must submit employment verification every 6 months'],
    limitations: ['Only for employed OKU individuals'],
    faq: [
      { question: 'How do I register?', answer: 'Register your OKU status with JKM first, then apply through this portal.' },
    ],
  },
  {
    id: 'btb',
    programName: 'Bantuan Anak Bujang',
    programCode: 'BTB',
    category: 'children',
    icon: '👨‍👩‍👧',
    currentBalance: 150,
    totalAllocated: 150,
    monthlyCredit: 150,
    nextCreditDate: '2024-02-01',
    expiryDate: null,
    remainingQuota: null,
    quotaUnit: 'RM',
    eligibilityStatus: 'eligible',
    applicationStatus: 'approved',
    isVerified: true,
    transactions: [
      { id: 't10', date: '2024-01-01', description: 'Monthly Credit', amount: 150, type: 'credit' },
    ],
    programDescription: 'BTB provides monthly assistance to families with unmarried dependent children.',
    eligibilityCriteria: [
      'Malaysian citizen',
      'Have unmarried children aged 18-21 in education',
      'B40 household',
    ],
    benefitAmount: 'RM150 per child per month',
    renewalRules: 'Annual verification of child education status.',
    conditions: ['Child must be enrolled in approved educational institution'],
    limitations: ['Maximum 3 children per household'],
    faq: [],
  },
  {
    id: 'bpt',
    programName: 'Bantuan Pesakit Kronik',
    programCode: 'BPT',
    category: 'medical',
    icon: '🏥',
    currentBalance: 200,
    totalAllocated: 200,
    monthlyCredit: 200,
    nextCreditDate: '2024-02-01',
    expiryDate: null,
    remainingQuota: 4,
    quotaUnit: 'visits',
    eligibilityStatus: 'pending',
    applicationStatus: 'documents_required',
    isVerified: false,
    alertMessage: '📢 Medical report required - submit now',
    alertType: 'warning',
    transactions: [],
    programDescription: 'BPT provides medical assistance to patients with chronic illnesses.',
    eligibilityCriteria: [
      'Malaysian citizen',
      'Diagnosed with chronic illness',
      'Under treatment at government hospital',
    ],
    benefitAmount: 'RM200 per month for medical expenses',
    renewalRules: 'Medical reassessment every 6 months.',
    conditions: ['Must attend scheduled medical appointments'],
    limitations: ['Only at government healthcare facilities'],
    faq: [],
  },
  {
    id: 'bkk',
    programName: 'Bantuan Kanak-Kanak',
    programCode: 'BKK',
    category: 'children',
    icon: '👶',
    currentBalance: 200,
    totalAllocated: 200,
    monthlyCredit: 100,
    nextCreditDate: '2024-02-01',
    expiryDate: null,
    remainingQuota: null,
    quotaUnit: 'RM',
    eligibilityStatus: 'eligible',
    applicationStatus: 'approved',
    isVerified: true,
    transactions: [
      { id: 't11', date: '2024-01-01', description: 'Monthly Credit', amount: 100, type: 'credit' },
      { id: 't12', date: '2023-12-01', description: 'Monthly Credit', amount: 100, type: 'credit' },
    ],
    programDescription: 'BKK provides monthly assistance for children below 6 years old from B40 families.',
    eligibilityCriteria: [
      'Malaysian citizen',
      'Child aged 0-6 years',
      'B40 household',
    ],
    benefitAmount: 'RM100 per child per month',
    renewalRules: 'Automatic until child turns 6.',
    conditions: ['Must update child status annually'],
    limitations: ['Ends when child turns 6'],
    faq: [],
  },
  {
    id: 'ba',
    programName: 'Bantuan Am',
    programCode: 'BA',
    category: 'groceries',
    icon: '🤲',
    currentBalance: 300,
    totalAllocated: 300,
    monthlyCredit: 300,
    nextCreditDate: '2024-02-01',
    expiryDate: null,
    remainingQuota: null,
    quotaUnit: 'RM',
    eligibilityStatus: 'eligible',
    applicationStatus: 'approved',
    isVerified: true,
    transactions: [
      { id: 't13', date: '2024-01-01', description: 'Monthly Credit', amount: 300, type: 'credit' },
    ],
    programDescription: 'Bantuan Am provides general financial assistance to those in need.',
    eligibilityCriteria: [
      'Malaysian citizen',
      'No fixed income',
      'Verified hardship case',
    ],
    benefitAmount: 'RM300 per month',
    renewalRules: 'Quarterly review of eligibility.',
    conditions: ['Must report any income changes'],
    limitations: ['Subject to available government budget'],
    faq: [],
  },
  {
    id: 'smue',
    programName: 'SMUE Skim Mesra Usia Emas',
    programCode: 'SMUE Selangor',
    category: 'selangor',
    icon: '🎂',
    currentBalance: 150,
    totalAllocated: 150,
    monthlyCredit: 0,
    nextCreditDate: null,
    expiryDate: '2024-12-31',
    remainingQuota: 150,
    quotaUnit: 'RM',
    eligibilityStatus: 'eligible',
    applicationStatus: 'approved',
    isVerified: true,
    alertMessage: '🎂 Birthday voucher available!',
    alertType: 'info',
    transactions: [],
    programDescription: 'SMUE Selangor provides yearly vouchers to Selangor senior citizens during their birthday month.',
    eligibilityCriteria: [
      'Selangor resident',
      'Aged 60 years and above',
      'Registered with SMUE program',
    ],
    benefitAmount: 'RM150 yearly (birthday month)',
    renewalRules: 'Annual automatic renewal.',
    conditions: ['Must redeem during birthday month'],
    limitations: ['Only for Selangor residents', 'Expires if not used in birthday month'],
    faq: [
      { question: 'When can I use SMUE?', answer: 'You can use your SMUE voucher during your birthday month at participating outlets.' },
    ],
  },
  {
    id: 'iss',
    programName: 'Iltizam Selangor Sihat',
    programCode: 'ISS',
    category: 'selangor',
    icon: '💊',
    currentBalance: 180,
    totalAllocated: 300,
    monthlyCredit: 0,
    nextCreditDate: null,
    expiryDate: '2024-12-31',
    remainingQuota: 3,
    quotaUnit: 'visits',
    eligibilityStatus: 'eligible',
    applicationStatus: 'approved',
    isVerified: true,
    transactions: [
      { id: 't14', date: '2024-01-20', description: 'Klinik Komuniti Seksyen 7', amount: -60, type: 'debit', merchant: 'Klinik Komuniti' },
      { id: 't15', date: '2024-01-05', description: 'Klinik Primer Shah Alam', amount: -60, type: 'debit', merchant: 'Klinik Primer' },
    ],
    allowedCategories: ['Medical consultation', 'Basic medication'],
    programDescription: 'ISS provides subsidized healthcare visits at participating clinics for Selangor residents.',
    eligibilityCriteria: [
      'Selangor resident',
      'B40 income group',
      'Valid Selangor address',
    ],
    benefitAmount: 'RM60 per visit, up to 5 visits per year',
    renewalRules: 'Annual renewal with eligibility check.',
    conditions: ['Must visit participating ISS clinics'],
    limitations: ['Maximum 5 visits per year', 'RM60 coverage per visit'],
    faq: [
      { question: 'Which clinics accept ISS?', answer: 'All Klinik Komuniti and participating Klinik Primer in Selangor.' },
    ],
  },
];

// Map colors to the new data
const colorMap: Record<string, string> = {
  sara: 'bg-gradient-to-br from-green-600 to-green-800',
  str: 'bg-gradient-to-br from-purple-600 to-purple-800',
  budi95: 'bg-gradient-to-br from-blue-600 to-blue-800',
  bwe: 'bg-gradient-to-br from-gray-500 to-gray-700',
  epoku: 'bg-gradient-to-br from-orange-500 to-orange-700',
  btb: 'bg-gradient-to-br from-indigo-500 to-indigo-700',
  bpt: 'bg-gradient-to-br from-red-500 to-red-700',
  bkk: 'bg-gradient-to-br from-teal-500 to-teal-700',
  ba: 'bg-gradient-to-br from-cyan-600 to-cyan-800',
  smue: 'bg-gradient-to-br from-red-600 to-yellow-600',
  iss: 'bg-gradient-to-br from-emerald-600 to-emerald-800',
};

export const SUBSIDY_PROGRAMS: SubsidyProgram[] = rawSubsidyWallets.map(wallet => ({
  ...wallet,
  color: colorMap[wallet.id] || 'bg-gradient-to-br from-gray-600 to-gray-800'
}));

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: '1',
    type: 'priority',
    title: 'Tax Filing Due',
    message: 'Your e-Filing submission is due in 3 days.',
    timestamp: '2 hours ago',
    isRead: false,
  },
  {
    id: '2',
    type: 'status',
    title: 'Application Status',
    message: 'Your STR appeal has been approved.',
    timestamp: '1 day ago',
    isRead: true,
  },
  {
    id: '3',
    type: 'news',
    title: 'New EV Incentives Announced',
    message: 'Government introduces new tax rebates for EV owners.',
    timestamp: '2 days ago',
    isRead: true,
    imageUrl: 'https://picsum.photos/100/100',
  },
];

export const STRINGS = {
  ms: {
    welcome: 'Selamat Datang',
    welcome_back: 'Selamat kembali',
    login_btn: 'Log masuk dengan MyDigital ID',
    verify_id: 'Sahkan Identiti',
    home: 'Utama',
    chat: 'Bantuan',
    notify: 'Notifikasi',
    personal: 'Profil',
    pay: 'Bayar / Imbas',
    view_details: 'Lihat Butiran',
    eligible: 'Layak',
    update_info: 'Kemaskini',
    confirm_verify: 'Sah & Hantar',
    renew_passport: 'Perbaharui Pasport',
    renew_license: 'Perbaharui Lesen',
    pay_roadtax: 'Bayar Cukai Jalan',
    share_details: 'Kongsi Butiran',
    biometric_msg: 'Imbas Wajah',
    payment_auth: 'Pengesahan Bayaran',
    urgent: 'PENTING',
    news: 'Berita Terkini',
    total_subsidies: 'Jumlah Subsidi',
    active: 'Aktif',
    pending: 'Menunggu',
    action_needed: 'Tindakan',
    search_placeholder: 'Cari subsidi anda',
    verified_id: 'Identiti Disahkan',
    personal_details: 'Butiran Peribadi',
    my_documents: 'Dokumen Saya',
    security_privacy: 'Keselamatan & Privasi',
    sign_out: 'Log Keluar',
    quick_actions: 'Tindakan Pantas',
    settings: 'Tetapan',
    apply_replacement: 'Mohon Ganti',
    renew_validity: 'Perbaharui Tempoh',
    due_soon: 'Tamat Tempoh',
    no_subsidies: 'Tiada subsidi ditemui.',
    ai_greeting: 'Hello, saya Marina!',
    ai_subtitle: 'Pembantu Maya Anda',
    input_placeholder: 'Taip mesej...',
    listening: 'Mendengar...',
    tab_overview: 'Gambaran',
    tab_wallet: 'Dompet',
    tab_info: 'Info',
    tab_apply: 'Mohon',
    // Wallet Details
    wallet_balance: 'Baki Dompet',
    total_allocated: 'Jumlah Diperuntukkan',
    monthly_credit: 'Kredit Bulanan',
    next_credit: 'Kredit Seterusnya',
    balance_expires: 'Baki Tamat Tempoh',
    transactions: 'Transaksi',
    see_all: 'Lihat Semua',
    no_transactions: 'Tiada transaksi terkini.',
    about_program: 'Tentang',
    benefit_amount: 'Jumlah Manfaat',
    eligibility_criteria: 'Kriteria Kelayakan',
    renewal_rules: 'Peraturan Pembaharuan',
    conditions: 'Syarat-syarat',
    limitations: 'Had Penggunaan',
    faq: 'Soalan Lazim',
    payment_methods: 'Kaedah Bayaran',
    start_refueling: 'Mula Isi Minyak',
    authorize_pump: 'Sahkan Pam',
    show_qr: 'Tunjuk QR',
    barcode: 'Kod Bar',
    secured_by_biometrics: 'Dilindungi Biometrik',
    subsidized_products: 'Produk Subsidi',
    eligible_items: 'Barangan Layak',
    participating_stores: 'Kedai Terlibat',
    shop_online: 'Beli Dalam Talian',
    find_maps: 'Cari di Peta',
    nearest_station: 'Stesen Terdekat',
    gps_active: 'GPS Aktif',
    recommended: 'Disyorkan',
    refueling_vehicle: 'Kenderaan',
    change: 'Tukar',
    panel_clinic: 'Lokasi Klinik Panel',
    applicant_details: 'Butiran Pemohon',
    full_name: 'Nama Penuh',
    ic_number: 'No. Kad Pengenalan',
    household_income: 'Pendapatan Isi Rumah',
    required_documents: 'Dokumen Diperlukan',
    income_proof: 'Bukti Pendapatan / Penyata Gaji',
    save_draft: 'Simpan Draf',
    submit_application: 'Hantar Permohonan',
    application_submitted: 'Permohonan Dihantar',
    pending_review: 'Kemaskini anda sedang disemak.',
    back_to_wallet: 'Kembali ke Dompet',
    please_ensure: 'Sila pastikan butiran tepat.',
    // Notifications
    notifications_title: 'Notifikasi',
    urgent_section: 'Penting',
    applications_section: 'Permohonan',
    news_section: 'Berita Terkini',
    due_in_3_days: 'Tamat dalam 3 hari',
    // AI Suggestions
    suggestion_str: 'Semak Status STR',
    suggestion_sara: 'Di mana boleh guna SARA?',
    suggestion_petrol: 'Cari stesen minyak terdekat',
    suggestion_history: 'Sejarah Bayaran Saya',
    // Wallet - Fuel & Payment (New)
    detected_location: 'Lokasi Dikesan',
    vehicle_plate: 'No. Plat Kenderaan',
    pump_number: 'Nombor Pam',
    pump_authorized: 'Pam Disahkan!',
    lift_nozzle: 'Anda boleh angkat nozel dan mula isi minyak di',
    limit_litres: 'Had',
    est_amount: 'Anggaran Jumlah',
    done_refueling: 'Selesai Isi Minyak',
    scan_to_pay: 'Imbas & Bayar',
    barcode_pay: 'Bayar Kod Bar',
    present_barcode: 'Tunjukkan kod bar ini kepada juruwang',
    close: 'Tutup',
    // Misc (New)
    delivery_available: 'Penghantaran Disediakan',
    pdf_limit: 'PDF atau JPG (Maks 5MB)',
    submitting: 'Menghantar...',
    no_schedule: 'Tiada Jadual',
  },
  en: {
    welcome: 'Welcome',
    welcome_back: 'Welcome back',
    login_btn: 'Login with MyDigital ID',
    verify_id: 'Verify Identity',
    home: 'Home',
    chat: 'Help',
    notify: 'Alerts',
    personal: 'Personal',
    pay: 'Pay / Scan',
    view_details: 'View Details',
    eligible: 'Eligible',
    update_info: 'Update Info',
    confirm_verify: 'Confirm & Verify',
    renew_passport: 'Renew Passport',
    renew_license: 'Renew License',
    pay_roadtax: 'Pay Road Tax',
    share_details: 'Share Details',
    biometric_msg: 'Face Scan',
    payment_auth: 'Authorize Payment',
    urgent: 'URGENT',
    news: 'Latest News',
    total_subsidies: 'Total Subsidies',
    active: 'Active',
    pending: 'Pending',
    action_needed: 'Action',
    search_placeholder: 'Search your subsidies',
    verified_id: 'Verified ID',
    personal_details: 'Personal Details',
    my_documents: 'My Documents',
    security_privacy: 'Security & Privacy',
    sign_out: 'Sign Out',
    quick_actions: 'Quick Actions',
    settings: 'Settings',
    apply_replacement: 'Apply for Replacement',
    renew_validity: 'Renew Validity',
    due_soon: 'Due Soon',
    no_subsidies: 'No subsidies found matching your criteria.',
    ai_greeting: "Hello, I'm Marina!",
    ai_subtitle: 'Your Virtual Assistant',
    input_placeholder: 'Type a message...',
    listening: 'Listening...',
    tab_overview: 'Overview',
    tab_wallet: 'Wallet',
    tab_info: 'Info',
    tab_apply: 'Apply',
    // Wallet Details
    wallet_balance: 'Wallet Balance',
    total_allocated: 'Total Allocated',
    monthly_credit: 'Monthly Credit',
    next_credit: 'Next Credit',
    balance_expires: 'Balance Expires',
    transactions: 'Transactions',
    see_all: 'See All',
    no_transactions: 'No recent transactions.',
    about_program: 'About',
    benefit_amount: 'Benefit Amount',
    eligibility_criteria: 'Eligibility Criteria',
    renewal_rules: 'Renewal Rules',
    conditions: 'Conditions',
    limitations: 'Limitations',
    faq: 'FAQ',
    payment_methods: 'Payment Methods',
    start_refueling: 'Start Refueling',
    authorize_pump: 'Authorize Pump',
    show_qr: 'Show QR',
    barcode: 'Barcode',
    secured_by_biometrics: 'Secured by Biometrics',
    subsidized_products: 'Subsidized Products',
    eligible_items: 'Eligible Items',
    participating_stores: 'Participating Stores',
    shop_online: 'Shop Online & Checkout',
    find_maps: 'Find on Maps',
    nearest_station: 'Nearest Station',
    gps_active: 'GPS Active',
    recommended: 'Recommended',
    refueling_vehicle: 'Refueling Vehicle',
    change: 'Change',
    panel_clinic: 'Panel Clinic Locator',
    applicant_details: 'Applicant Details',
    full_name: 'Full Name',
    ic_number: 'MyKad / IC Number',
    household_income: 'Household Income',
    required_documents: 'Required Documents',
    income_proof: 'Income Proof / Payslip',
    save_draft: 'Save Draft',
    submit_application: 'Submit Application',
    application_submitted: 'Application Submitted',
    pending_review: 'Your update is now pending review.',
    back_to_wallet: 'Back to Wallet',
    please_ensure: 'Please ensure all details are accurate.',
    // Notifications
    notifications_title: 'Notifications',
    urgent_section: 'Urgent',
    applications_section: 'Applications',
    news_section: 'Latest News',
    due_in_3_days: 'Due in 3 days',
    // AI Suggestions
    suggestion_str: 'Check STR Status',
    suggestion_sara: 'Where can I use SARA?',
    suggestion_petrol: 'Find nearest petrol station',
    suggestion_history: 'My Payment History',
    // Wallet - Fuel & Payment (New)
    detected_location: 'Detected Location',
    vehicle_plate: 'Vehicle Plate',
    pump_number: 'Pump Number',
    pump_authorized: 'Pump Authorized!',
    lift_nozzle: 'You may lift the nozzle and start refueling at',
    limit_litres: 'Limit',
    est_amount: 'Est. Amount',
    done_refueling: 'Done Refueling',
    scan_to_pay: 'Scan to Pay',
    barcode_pay: 'Barcode Pay',
    present_barcode: 'Present this barcode to the cashier',
    close: 'Close',
    // Misc (New)
    delivery_available: 'Delivery Available',
    pdf_limit: 'PDF or JPG (Max 5MB)',
    submitting: 'Submitting...',
    no_schedule: 'No Schedule',
  },
  zh: {
    welcome: '欢迎',
    welcome_back: '欢迎回来',
    login_btn: '使用 MyDigital ID 登录',
    verify_id: '验证身份',
    home: '主页',
    chat: '帮助',
    notify: '通知',
    personal: '个人',
    pay: '支付 / 扫描',
    view_details: '查看详情',
    eligible: '符合资格',
    update_info: '更新信息',
    confirm_verify: '确认并验证',
    renew_passport: '更新护照',
    renew_license: '更新驾照',
    pay_roadtax: '支付路税',
    share_details: '分享详情',
    biometric_msg: '面部扫描',
    payment_auth: '支付授权',
    urgent: '紧急',
    news: '最新新闻',
    total_subsidies: '补贴总额',
    active: '活跃',
    pending: '待处理',
    action_needed: '需行动',
    search_placeholder: '搜索您的补贴',
    verified_id: '身份已验证',
    personal_details: '个人资料',
    my_documents: '我的文件',
    security_privacy: '安全与隐私',
    sign_out: '登出',
    quick_actions: '快速操作',
    settings: '设置',
    apply_replacement: '申请补发',
    renew_validity: '更新有效期',
    due_soon: '即将到期',
    no_subsidies: '未找到符合条件的补贴。',
    ai_greeting: '你好，我是 Marina！',
    ai_subtitle: '您的虚拟助手',
    input_placeholder: '输入消息...',
    listening: '正在聆听...',
    tab_overview: '概览',
    tab_wallet: '钱包',
    tab_info: '信息',
    tab_apply: '申请',
    // Wallet Details
    wallet_balance: '钱包余额',
    total_allocated: '总分配额',
    monthly_credit: '每月额度',
    next_credit: '下次发放',
    balance_expires: '余额到期',
    transactions: '交易记录',
    see_all: '查看全部',
    no_transactions: '无近期交易。',
    about_program: '关于',
    benefit_amount: '福利金额',
    eligibility_criteria: '资格标准',
    renewal_rules: '更新规则',
    conditions: '条款条件',
    limitations: '使用限制',
    faq: '常见问题',
    payment_methods: '支付方式',
    start_refueling: '开始加油',
    authorize_pump: '授权油泵',
    show_qr: '显示二维码',
    barcode: '条形码',
    secured_by_biometrics: '生物识别保护',
    subsidized_products: '补贴商品',
    eligible_items: '符合资格物品',
    participating_stores: '参与商店',
    shop_online: '在线购物',
    find_maps: '地图查找',
    nearest_station: '最近油站',
    gps_active: 'GPS 已激活',
    recommended: '推荐',
    refueling_vehicle: '加油车辆',
    change: '更改',
    panel_clinic: '指定诊所定位',
    applicant_details: '申请人详情',
    full_name: '全名',
    ic_number: '身份证号码',
    household_income: '家庭收入',
    required_documents: '所需文件',
    income_proof: '收入证明 / 工资单',
    save_draft: '保存草稿',
    submit_application: '提交申请',
    application_submitted: '申请已提交',
    pending_review: '您的更新正在审核中。',
    back_to_wallet: '返回钱包',
    please_ensure: '请确保所有详细信息准确无误。',
    // Notifications
    notifications_title: '通知',
    urgent_section: '紧急',
    applications_section: '申请',
    news_section: '最新消息',
    due_in_3_days: '3天后截止',
    // AI Suggestions
    suggestion_str: '检查 STR 状态',
    suggestion_sara: '哪里可以使用 SARA？',
    suggestion_petrol: '寻找最近的加油站',
    suggestion_history: '我的支付历史',
    // Wallet - Fuel & Payment (New)
    detected_location: '检测到位置',
    vehicle_plate: '车牌号码',
    pump_number: '油泵号码',
    pump_authorized: '油泵已授权！',
    lift_nozzle: '您可以在此开始加油',
    limit_litres: '限制',
    est_amount: '预计金额',
    done_refueling: '完成加油',
    scan_to_pay: '扫描支付',
    barcode_pay: '条码支付',
    present_barcode: '向收银员出示此条码',
    close: '关闭',
    // Misc (New)
    delivery_available: '提供送货',
    pdf_limit: 'PDF 或 JPG (最大 5MB)',
    submitting: '正在提交...',
    no_schedule: '无时间表',
  },
  ta: {
    welcome: 'வரவேற்பு',
    welcome_back: 'நல்வரவு',
    login_btn: 'MyDigital ID மூலம் உள்நுழைக',
    verify_id: 'அடையாளத்தைச் சரிபார்க்கவும்',
    home: 'முகப்பு',
    chat: 'உதவி',
    notify: 'அறிவிப்புகள்',
    personal: 'தனிப்பட்டவை',
    pay: 'செலுத்து / ஸ்கேன்',
    view_details: 'விவரங்களைக் காண்க',
    eligible: 'தகுதியானவர்',
    update_info: 'தகவலைப் புதுப்பிக்கவும்',
    confirm_verify: 'உறுதிசெய்து சரிபார்க்கவும்',
    renew_passport: 'கடவுச்சீட்டைப் புதுப்பிக்கவும்',
    renew_license: 'உரிமத்தைப் புதுப்பிக்கவும்',
    pay_roadtax: 'சாலை வரி செலுத்துங்கள்',
    share_details: 'விவரங்களைப் பகிரவும்',
    biometric_msg: 'முக ஸ்கேன்',
    payment_auth: 'கட்டண அங்கீகாரம்',
    urgent: 'அவசரம்',
    news: 'சமீபத்திய செய்திகள்',
    total_subsidies: 'மொத்த மானியங்கள்',
    active: 'செயலில்',
    pending: 'நிலுவையில்',
    action_needed: 'செயல்',
    search_placeholder: 'உங்கள் மானியங்களைத் தேடுங்கள்',
    verified_id: 'சரிபார்க்கப்பட்டது',
    personal_details: 'தனிப்பட்ட விவரங்கள்',
    my_documents: 'எனது ஆவணங்கள்',
    security_privacy: 'பாதுகாப்பு & தனியுரிமை',
    sign_out: 'வெளியேறு',
    quick_actions: 'விரைவான செயல்கள்',
    settings: 'அமைப்புகள்',
    apply_replacement: 'மாற்று விண்ணப்பிக்கவும்',
    renew_validity: 'புதுப்பிக்கவும்',
    due_soon: 'விரைவில் காலாவதியாகிறது',
    no_subsidies: 'மானியங்கள் எதுவும் இல்லை.',
    ai_greeting: 'வணக்கம், நான் Marina!',
    ai_subtitle: 'உங்கள் மெய்நிகர் உதவியாளர்',
    input_placeholder: 'செய்தியை உள்ளிடவும்...',
    listening: 'கேட்கிறது...',
    tab_overview: 'கண்ணோட்டம்',
    tab_wallet: 'பணப்பை',
    tab_info: 'தகவல்',
    tab_apply: 'விண்ணப்பிக்க',
    // Wallet Details
    wallet_balance: 'பணப்பை இருப்பு',
    total_allocated: 'ஒதுக்கப்பட்ட மொத்தம்',
    monthly_credit: 'மாத வரவு',
    next_credit: 'அடுத்த வரவு',
    balance_expires: 'இருப்பு காலாவதியாகிறது',
    transactions: 'பரிவர்த்தனைகள்',
    see_all: 'அனைத்தையும் காண்க',
    no_transactions: 'சமீபத்திய பரிவர்த்தனைகள் இல்லை.',
    about_program: 'பற்றி',
    benefit_amount: 'நன்மைகளின் தொகை',
    eligibility_criteria: 'தகுதி வரம்புகள்',
    renewal_rules: 'புதுப்பித்தல் விதிகள்',
    conditions: 'நிபந்தனைகள்',
    limitations: 'வரம்புகள்',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    payment_methods: 'கட்டண முறைகள்',
    start_refueling: 'எரிபொருள் நிரப்பத் தொடங்குங்கள்',
    authorize_pump: 'பம்பை அங்கீகரிக்கவும்',
    show_qr: 'QR குறியீட்டைக் காட்டு',
    barcode: 'பார்கோடு',
    secured_by_biometrics: 'பயோமெட்ரிக் மூலம் பாதுகாக்கப்பட்டது',
    subsidized_products: 'மானிய பொருட்கள்',
    eligible_items: 'தகுதியான பொருட்கள்',
    participating_stores: 'பங்கேற்கும் கடைகள்',
    shop_online: 'ஆன்லைனில் வாங்கவும்',
    find_maps: 'வரைபடத்தில் தேடவும்',
    nearest_station: 'அருகிலுள்ள நிலையம்',
    gps_active: 'GPS செயலில் உள்ளது',
    recommended: 'பரிந்துரைக்கப்படுகிறது',
    refueling_vehicle: 'வாகனம்',
    change: 'மாற்றவும்',
    panel_clinic: 'மருத்துவமனை இருப்பிடம்',
    applicant_details: 'விண்ணப்பதாரர் விவரங்கள்',
    full_name: 'முழு பெயர்',
    ic_number: 'அடையாள அட்டை எண்',
    household_income: 'குடும்ப வருமானம்',
    required_documents: 'தேவையான ஆவணங்கள்',
    income_proof: 'வருமானச் சான்று',
    save_draft: 'வரைவைச் சேமிக்கவும்',
    submit_application: 'விண்ணப்பத்தைச் சமர்ப்பிக்கவும்',
    application_submitted: 'விண்ணப்பம் சமர்ப்பிக்கப்பட்டது',
    pending_review: 'உங்கள் புதுப்பிப்பு மதிப்பாய்வில் உள்ளது.',
    back_to_wallet: 'பணப்பைக்குத் திரும்பு',
    please_ensure: 'எல்லா விவரங்களும் துல்லியமாக இருப்பதை உறுதி செய்யவும்.',
    // Notifications
    notifications_title: 'அறிவிப்புகள்',
    urgent_section: 'அவசரம்',
    applications_section: 'விண்ணப்பங்கள்',
    news_section: 'சமீபத்திய செய்திகள்',
    due_in_3_days: '3 நாட்களில் காலாவதியாகிறது',
    // AI Suggestions
    suggestion_str: 'STR நிலையைச் சரிபார்க்கவும்',
    suggestion_sara: 'SARA-வை எங்கு பயன்படுத்தலாம்?',
    suggestion_petrol: 'அருகிலுள்ள பெட்ரோல் நிலையத்தைக் கண்டறியவும்',
    suggestion_history: 'எனது கட்டண வரலாறு',
    // Wallet - Fuel & Payment (New)
    detected_location: 'கண்டறியப்பட்ட இடம்',
    vehicle_plate: 'வாகன எண் பலகை',
    pump_number: 'பம்ப் எண்',
    pump_authorized: 'பம்ப் அங்கீகரிக்கப்பட்டது!',
    lift_nozzle: 'நீங்கள் முனையை உயர்த்தி எரிபொருள் நிரப்பலாம்',
    limit_litres: 'வரம்பு',
    est_amount: 'மதிப்பிடப்பட்ட தொகை',
    done_refueling: 'எரிபொருள் நிரப்புதல் முடிந்தது',
    scan_to_pay: 'செலுத்த ஸ்கேன் செய்யவும்',
    barcode_pay: 'பார்கோடு கட்டணம்',
    present_barcode: 'காசாளரிடம் இந்த பார்கோடை காட்டவும்',
    close: 'மூடு',
    // Misc (New)
    delivery_available: 'டெலிவரி கிடைக்கிறது',
    pdf_limit: 'PDF அல்லது JPG (அதிகபட்சம் 5MB)',
    submitting: 'சமர்ப்பிக்கிறது...',
    no_schedule: 'அட்டவணை இல்லை',
  }
};
